---
version: '2'
services:

  postgres:
    image: debezium/postgres:11
    environment:
      POSTGRES_PASSWORD: postgres
    command: postgres -c config_file=/home/config/postgresql.conf
    ports:
      - 5432:5432
    volumes:
      - $PWD:/home/config

  
